"""Generate GitHub issue templates from scored papers."""
from typing import Optional
from agents.maintainer_researcher.models import PaperMetadata


def generate_issue_title(
    paper_title: str,
    paper_authors: str,
    issue_type: str
) -> str:
    """Generate concise GitHub issue title from paper metadata."""
    clean_title = paper_title.replace(":", " -").strip()
    if len(clean_title) > 80:
        clean_title = clean_title[:77] + "..."
    return f"[{issue_type.upper()}] {clean_title}"


def generate_issue_body(
    metadata: PaperMetadata,
    implementability_score: float,
    strategic_value_score: float,
    maintainer_relevance_score: float,
    overall_score: float,
    suggested_tags: str
) -> str:
    """Generate detailed GitHub issue body from paper data."""
    body = f"""## Paper Summary

**Title:** {metadata.title}

**Authors:** {metadata.authors}

**Publication Date:** {metadata.publication_date}

**Paper Link:** {metadata.url}

### Abstract

{metadata.abstract}

## Relevance Assessment

| Metric | Score |
|--------|-------|
| Implementability | {implementability_score:.1f}/100 |
| Strategic Value | {strategic_value_score:.1f}/100 |
| Maintainer Relevance | {maintainer_relevance_score:.1f}/100 |
| **Overall** | **{overall_score:.1f}/100** |

## Suggested Issue Tags

{suggested_tags}

## Next Steps

1. Review the paper abstract and linked PDF
2. Assess implementation effort
3. Determine if this should become a feature/enhancement
4. If viable, break down into actionable sub-tasks

---
*Generated by MaintainerResearcherAgent from arXiv paper {metadata.paper_id}*
"""
    return body


def create_draft_github_issue(
    metadata: PaperMetadata,
    implementability_score: float,
    strategic_value_score: float,
    maintainer_relevance_score: float,
    overall_score: float,
    suggested_tags: str,
    issue_type: str = "feature"
) -> dict:
    """Create a draft GitHub issue dict (not posted, just prepared)."""
    title = generate_issue_title(metadata.title, metadata.authors, issue_type)
    body = generate_issue_body(
        metadata,
        implementability_score,
        strategic_value_score,
        maintainer_relevance_score,
        overall_score,
        suggested_tags
    )

    return {
        "title": title,
        "body": body,
        "labels": [issue_type, "research-based", "automated"],
        "paper_id": metadata.paper_id,
        "paper_url": metadata.url
    }
