# shared/models.py
"""
SQLAlchemy ORM models for all core tables.
Persists all trading data, audit trails, and analytics.
"""
from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Boolean, JSON,
    ForeignKey, Index, Enum as SQLEnum
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum

Base = declarative_base()


class TradeStatus(str, enum.Enum):
    PENDING = "pending"
    EXECUTED = "executed"
    REJECTED = "rejected"
    FAILED = "failed"


class PortfolioState(Base):
    """Hourly portfolio snapshot."""
    __tablename__ = "portfolio_state"

    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)
    account_id = Column(String(255), index=True)
    cash = Column(Float)  # Available cash
    total_value = Column(Float)  # Total account value
    peak_value = Column(Float)  # Peak value (for drawdown calculation)
    open_positions_count = Column(Integer, default=0)
    drawdown_pct = Column(Float, default=0.0)

    # Relationships
    trades = relationship("Trade", back_populates="portfolio_state")

    __table_args__ = (
        Index('idx_portfolio_account_timestamp', 'account_id', 'timestamp'),
    )


class Trade(Base):
    """Individual trade record."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True)
    portfolio_state_id = Column(Integer, ForeignKey("portfolio_state.id"))

    # Trade details
    symbol = Column(String(50), index=True)
    action = Column(String(10))  # "long" or "short"
    quantity = Column(Float)
    entry_price = Column(Float)
    exit_price = Column(Float, nullable=True)

    # Decision metadata
    consensus_score = Column(Float)
    confidence = Column(Float)
    regime = Column(String(50))  # expansion, crisis, pandemic
    agent_signals = Column(JSON)  # {"technical": 0.8, "sentiment": 0.7}

    # Execution
    status = Column(SQLEnum(TradeStatus), default=TradeStatus.PENDING, index=True)
    rejection_reason = Column(String(500), nullable=True)
    risk_check_reason = Column(String(500), nullable=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)
    executed_at = Column(DateTime(timezone=True), nullable=True)

    # P&L
    pnl = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)

    # Relationships
    portfolio_state = relationship("PortfolioState", back_populates="trades")
    broker_fills = relationship("BrokerFill", back_populates="trade")

    __table_args__ = (
        Index('idx_trades_symbol_created', 'symbol', 'created_at'),
        Index('idx_trades_status_created', 'status', 'created_at'),
    )


class BrokerFill(Base):
    """Per-broker execution result."""
    __tablename__ = "broker_fills"

    id = Column(Integer, primary_key=True)
    trade_id = Column(Integer, ForeignKey("trades.id"))

    broker_name = Column(String(50), index=True)  # alpaca, ib, capital_com
    status = Column(String(50))  # filled, partial, error, rejected
    fill_price = Column(Float, nullable=True)
    fill_qty = Column(Float, nullable=True)
    commission = Column(Float, default=0.0)
    error_msg = Column(String(500), nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)

    # Relationships
    trade = relationship("Trade", back_populates="broker_fills")

    __table_args__ = (
        Index('idx_broker_fills_broker_created', 'broker_name', 'created_at'),
    )


class Signal(Base):
    """Signal generated by analysis agent."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True)

    # Agent & signal
    agent_name = Column(String(100), index=True)
    symbol = Column(String(50), index=True)
    signal_type = Column(String(50))  # bullish_signal, bearish_signal, neutral
    confidence = Column(Float)
    regime = Column(String(50))

    # Context
    reasoning = Column(String(1000))
    metadata = Column(JSON)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)

    # Relationships
    outcomes = relationship("SignalOutcome", back_populates="signal")

    __table_args__ = (
        Index('idx_signals_agent_symbol', 'agent_name', 'symbol'),
        Index('idx_signals_created', 'created_at'),
    )


class SignalOutcome(Base):
    """Win/loss for signal (used to update agent memory)."""
    __tablename__ = "signal_outcomes"

    id = Column(Integer, primary_key=True)
    signal_id = Column(Integer, ForeignKey("signals.id"))

    # Outcome
    won = Column(Boolean)  # True = profitable, False = loss
    pnl = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)

    closed_at = Column(DateTime(timezone=True), index=True)

    # Relationships
    signal = relationship("Signal", back_populates="outcomes")


class AgentStats(Base):
    """Per-agent performance statistics by regime."""
    __tablename__ = "agent_stats"

    id = Column(Integer, primary_key=True)

    agent_name = Column(String(100), index=True)
    regime = Column(String(50), index=True)

    # Performance
    total_signals = Column(Integer, default=0)
    winning_signals = Column(Integer, default=0)
    losing_signals = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)

    # Confidence adjustment
    confidence_multiplier = Column(Float, default=1.0)

    last_updated = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index('idx_agent_stats_agent_regime', 'agent_name', 'regime'),
    )


class BacktestResult(Base):
    """Historical backtest results."""
    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True)

    # Backtest metadata
    name = Column(String(255))
    start_date = Column(DateTime(timezone=True))
    end_date = Column(DateTime(timezone=True))
    starting_capital = Column(Float)

    # Results
    ending_capital = Column(Float)
    total_return_pct = Column(Float)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)
    sharpe_ratio = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float)

    # Details
    trades_log = Column(JSON)  # Full trade-by-trade results

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class InvestorReport(Base):
    """Monthly investor report."""
    __tablename__ = "investor_reports"

    id = Column(Integer, primary_key=True)

    # Report metadata
    investor_id = Column(String(255), index=True)
    month = Column(String(7), index=True)  # YYYY-MM

    # Performance
    starting_capital = Column(Float)
    ending_capital = Column(Float)
    monthly_return_pct = Column(Float)
    sharpe_ratio = Column(Float)
    max_drawdown_pct = Column(Float)

    # Details
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    top_trades = Column(JSON)  # List of top 5 trades
    regime_timeline = Column(JSON)  # Regime changes during month

    # Report
    pdf_url = Column(String(500), nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    sent_at = Column(DateTime(timezone=True), nullable=True)


class RiskEvent(Base):
    """Risk events: drawdown, broker failure, circuit breaker trip."""
    __tablename__ = "risk_events"

    id = Column(Integer, primary_key=True)

    event_type = Column(String(50), index=True)  # drawdown, broker_failure, circuit_breaker, hedge_activation
    severity = Column(String(20))  # warning, critical

    # Details
    message = Column(String(500))
    metadata = Column(JSON)  # Event-specific data

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        Index('idx_risk_events_type_created', 'event_type', 'created_at'),
    )


class OptimizerProposal(Base):
    """Parameter optimization proposals."""
    __tablename__ = "optimizer_proposals"

    id = Column(Integer, primary_key=True)

    # Proposal
    agent_name = Column(String(100))
    regime = Column(String(50))
    parameter = Column(String(255))
    current_value = Column(String(255))
    proposed_value = Column(String(255))
    reason = Column(String(500))

    # Decision
    approved = Column(Boolean, nullable=True)  # None = pending, True/False = decided
    approved_at = Column(DateTime(timezone=True), nullable=True)
    approved_by = Column(String(255), nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index('idx_proposals_agent_regime', 'agent_name', 'regime'),
    )


class OptimizerHistory(Base):
    """Audit trail of parameter changes."""
    __tablename__ = "optimizer_history"

    id = Column(Integer, primary_key=True)

    agent_name = Column(String(100))
    regime = Column(String(50))
    parameter = Column(String(255))
    old_value = Column(String(255))
    new_value = Column(String(255))
    reason = Column(String(500))

    applied_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index('idx_optimizer_history_agent', 'agent_name'),
    )


class CircuitBreakerLog(Base):
    """Circuit breaker events."""
    __tablename__ = "circuit_breaker_log"

    id = Column(Integer, primary_key=True)

    account_id = Column(String(255), index=True)
    status = Column(String(50))  # tripped, reset
    loss_pct = Column(Float)
    portfolio_value = Column(Float)
    peak_value = Column(Float)
    reason = Column(String(500))

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)

    __table_args__ = (
        Index('idx_cb_account_created', 'account_id', 'created_at'),
    )


class CorrelationHedgeLog(Base):
    """Correlation hedging activity."""
    __tablename__ = "correlation_hedge_log"

    id = Column(Integer, primary_key=True)

    action = Column(String(50))  # activate, deactivate, adjust
    portfolio_correlation = Column(Float)
    spy_price = Column(Float)
    hedge_qty = Column(Float)
    hedge_value = Column(Float, nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), index=True)

    __table_args__ = (
        Index('idx_hedge_created', 'created_at'),
    )
